import React, { useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  TextInput,
  Alert,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { StackScreenProps } from '@react-navigation/stack';
import { analyzeSymptoms as analyzeSymptomsService, SymptomAnalysisResult, ServiceError } from '../../services';
import { RootStackParamList } from '../../navigation/types';

type Props = StackScreenProps<RootStackParamList, 'AISymptomChecker'>;

const AISymptomCheckerScreen = ({ navigation }: Props) => {
  const [symptoms, setSymptoms] = useState('');
  const [duration, setDuration] = useState('');
  const [severity, setSeverity] = useState<'mild' | 'moderate' | 'severe' | ''>('');
  const [additionalInfo, setAdditionalInfo] = useState('');
  const [analysis, setAnalysis] = useState<SymptomAnalysisResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const severityOptions: { label: string; value: 'mild' | 'moderate' | 'severe'; color: string }[] = [
    { label: 'Mild', value: 'mild', color: '#4CAF50' },
    { label: 'Moderate', value: 'moderate', color: '#FF9800' },
    { label: 'Severe', value: 'severe', color: '#F44336' },
  ];

  const durationOptions = [
    'Less than 1 day',
    '1-3 days',
    '3-7 days',
    '1-2 weeks',
    'More than 2 weeks',
  ];

  const handleAnalyze = async () => {
    if (!symptoms.trim()) {
      Alert.alert('Error', 'Please describe your symptoms');
      return;
    }

    setLoading(true);
    setErrorMessage(null);
    try {
      const result = await analyzeSymptomsService({
        symptoms,
        durationDescription: duration || undefined,
        severity: severity || undefined,
        additionalInfo: additionalInfo || undefined,
      });
      setAnalysis(result);
    } catch (error) {
      const message = error instanceof ServiceError ? error.message : 'Failed to analyze symptoms. Please try again.';
      setErrorMessage(message);
      Alert.alert('Error', message);
    } finally {
      setLoading(false);
    }
  };

  const likelihoodToPercent = (likelihood: 'low' | 'moderate' | 'high') => {
    switch (likelihood) {
      case 'high': return 80;
      case 'moderate': return 50;
      case 'low': return 20;
    }
  };

  const renderConditionCard = (condition: SymptomAnalysisResult['possibleConditions'][number], index: number) => (
    <View key={index} style={styles.conditionCard}>
      <View style={styles.conditionHeader}>
        <Text style={styles.conditionName}>{condition.name}</Text>
        <View style={styles.probabilityContainer}>
          <Text style={styles.probabilityText}>{condition.likelihood}</Text>
        </View>
      </View>
      <Text style={styles.conditionDescription}>{condition.description}</Text>
      <View style={styles.probabilityBar}>
        <View
          style={[
            styles.probabilityFill,
            { width: `${likelihoodToPercent(condition.likelihood)}%` },
          ]}
        />
      </View>
    </View>
  );

  return (
    <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => navigation.goBack()}
          accessibilityRole="button"
          accessibilityLabel="Go back"
        >
          <Ionicons name="arrow-back" size={24} color="#2196F3" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>AI Symptom Checker</Text>
        <View style={styles.placeholder} />
      </View>

      {!analysis ? (
        <View style={styles.formContainer}>
          <View style={styles.aiNoticeContainer}>
            <Ionicons name="information-circle-outline" size={18} color="#1976D2" />
            <Text style={styles.aiNoticeText}>
              Responses are generated by an AI model (Google Gemini) and are not a medical diagnosis.
            </Text>
          </View>

          {errorMessage && (
            <View style={styles.errorBanner}>
              <Ionicons name="alert-circle" size={18} color="#F44336" />
              <Text style={styles.errorBannerText}>{errorMessage}</Text>
            </View>
          )}

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Describe Your Symptoms</Text>
            <TextInput
              style={styles.symptomsInput}
              placeholder="Tell us about your symptoms in detail..."
              value={symptoms}
              onChangeText={setSymptoms}
              multiline
              numberOfLines={4}
              textAlignVertical="top"
            />
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>How long have you had these symptoms?</Text>
            <ScrollView horizontal showsHorizontalScrollIndicator={false}>
              <View style={styles.optionsContainer}>
                {durationOptions.map((option, index) => (
                  <TouchableOpacity
                    key={index}
                    style={[
                      styles.optionButton,
                      duration === option && styles.optionButtonSelected,
                    ]}
                    onPress={() => setDuration(option)}
                  >
                    <Text
                      style={[
                        styles.optionButtonText,
                        duration === option && styles.optionButtonTextSelected,
                      ]}
                    >
                      {option}
                    </Text>
                  </TouchableOpacity>
                ))}
              </View>
            </ScrollView>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>How severe are your symptoms?</Text>
            <View style={styles.severityContainer}>
              {severityOptions.map((option, index) => (
                <TouchableOpacity
                  key={index}
                  style={[
                    styles.severityButton,
                    severity === option.value && styles.severityButtonSelected,
                    { borderColor: option.color },
                  ]}
                  onPress={() => setSeverity(option.value)}
                >
                  <View style={[styles.severityIndicator, { backgroundColor: option.color }]} />
                  <Text
                    style={[
                      styles.severityButtonText,
                      severity === option.value && styles.severityButtonTextSelected,
                    ]}
                  >
                    {option.label}
                  </Text>
                </TouchableOpacity>
              ))}
            </View>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Additional Information (Optional)</Text>
            <TextInput
              style={styles.additionalInput}
              placeholder="Any other relevant information about your health..."
              value={additionalInfo}
              onChangeText={setAdditionalInfo}
              multiline
              numberOfLines={3}
              textAlignVertical="top"
            />
          </View>

          <TouchableOpacity
            style={[styles.analyzeButton, loading && styles.analyzeButtonDisabled]}
            onPress={handleAnalyze}
            disabled={loading}
          >
            <LinearGradient
              colors={['#2196F3', '#1976D2']}
              style={styles.analyzeButtonGradient}
            >
              <Ionicons name="bulb-outline" size={20} color="white" />
              <Text style={styles.analyzeButtonText}>
                {loading ? 'Analyzing...' : 'Analyze Symptoms'}
              </Text>
            </LinearGradient>
          </TouchableOpacity>
        </View>
      ) : (
        <View style={styles.resultsContainer}>
          <View style={styles.resultsHeader}>
            <Ionicons name="checkmark-circle" size={32} color="#4CAF50" />
            <Text style={styles.resultsTitle}>Analysis Complete</Text>
            <Text style={styles.confidenceText}>Generated by AI — not a diagnosis</Text>
          </View>

          <View style={styles.urgencyContainer}>
            <View style={[
              styles.urgencyBadge,
              { backgroundColor: analysis.urgency === 'high' ? '#F44336' : 
                              analysis.urgency === 'medium' ? '#FF9800' : '#4CAF50' }
            ]}>
              <Text style={styles.urgencyText}>
                {analysis.urgency.toUpperCase()} PRIORITY
              </Text>
            </View>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Possible Conditions</Text>
            {analysis.possibleConditions.map(renderConditionCard)}
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Recommendations</Text>
            {analysis.recommendations.map((recommendation: string, index: number) => (
              <View key={index} style={styles.recommendationItem}>
                <Ionicons name="checkmark" size={16} color="#4CAF50" />
                <Text style={styles.recommendationText}>{recommendation}</Text>
              </View>
            ))}
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Suggested Specialists</Text>
            <View style={styles.specialistsContainer}>
              {analysis.suggestedSpecialists.map((specialist: string, index: number) => (
                // Note: this previously called navigate('Doctors', { specialty }),
                // but 'Doctors' is a tab inside PatientMain, not a root-stack
                // screen, and DoctorDirectoryScreen never read a `specialty`
                // route param anyway — the deep link would have silently
                // failed at runtime. PatientMain is typed as taking no
                // params (see RootStackParamList), so the honest fix is to
                // return the user to the patient app, where they can open
                // the doctor directory themselves, rather than pretend to
                // pre-filter by specialty.
                <TouchableOpacity
                  key={index}
                  style={styles.specialistButton}
                  onPress={() => navigation.navigate('PatientMain')}
                  accessibilityRole="button"
                  accessibilityLabel={`Find a ${specialist}`}
                >
                  <Ionicons name="medical-outline" size={20} color="#2196F3" />
                  <Text style={styles.specialistButtonText}>{specialist}</Text>
                </TouchableOpacity>
              ))}
            </View>
          </View>

          <View style={styles.disclaimerContainer}>
            <Ionicons name="warning-outline" size={20} color="#FF9800" />
            <Text style={styles.disclaimerText}>{analysis.disclaimer}</Text>
          </View>

          <TouchableOpacity
            style={styles.newAnalysisButton}
            onPress={() => {
              setAnalysis(null);
              setSymptoms('');
              setDuration('');
              setSeverity('');
              setAdditionalInfo('');
            }}
          >
            <Text style={styles.newAnalysisButtonText}>Start New Analysis</Text>
          </TouchableOpacity>
        </View>
      )}
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  aiNoticeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E3F2FD',
    padding: 12,
    borderRadius: 12,
    marginHorizontal: 20,
    marginTop: 20,
    gap: 8,
  },
  aiNoticeText: {
    flex: 1,
    fontSize: 12,
    color: '#1565C0',
    lineHeight: 16,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFEBEE',
    padding: 12,
    borderRadius: 12,
    marginHorizontal: 20,
    marginTop: 12,
    gap: 8,
  },
  errorBannerText: {
    color: '#C62828',
    fontSize: 14,
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: 'white',
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  placeholder: {
    width: 40,
  },
  formContainer: {
    padding: 20,
  },
  section: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  symptomsInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    color: '#333',
    backgroundColor: '#FAFAFA',
    minHeight: 100,
  },
  optionsContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  optionButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  optionButtonSelected: {
    backgroundColor: '#2196F3',
    borderColor: '#2196F3',
  },
  optionButtonText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  optionButtonTextSelected: {
    color: 'white',
  },
  severityContainer: {
    gap: 10,
  },
  severityButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 12,
    borderWidth: 2,
    backgroundColor: '#FAFAFA',
  },
  severityButtonSelected: {
    backgroundColor: '#E3F2FD',
  },
  severityIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 12,
  },
  severityButtonText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  severityButtonTextSelected: {
    color: '#2196F3',
  },
  additionalInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    color: '#333',
    backgroundColor: '#FAFAFA',
    minHeight: 80,
  },
  analyzeButton: {
    margin: 20,
    borderRadius: 12,
    overflow: 'hidden',
  },
  analyzeButtonDisabled: {
    opacity: 0.6,
  },
  analyzeButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  analyzeButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  resultsContainer: {
    padding: 20,
  },
  resultsHeader: {
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    marginBottom: 15,
  },
  resultsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 10,
    marginBottom: 5,
  },
  confidenceText: {
    fontSize: 14,
    color: '#666',
  },
  urgencyContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  urgencyBadge: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
  },
  urgencyText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  conditionCard: {
    backgroundColor: '#FAFAFA',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
  },
  conditionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  conditionName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  probabilityContainer: {
    backgroundColor: '#2196F3',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  probabilityText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  conditionDescription: {
    fontSize: 14,
    color: '#666',
    marginBottom: 10,
  },
  probabilityBar: {
    height: 4,
    backgroundColor: '#E0E0E0',
    borderRadius: 2,
    overflow: 'hidden',
  },
  probabilityFill: {
    height: '100%',
    backgroundColor: '#2196F3',
  },
  recommendationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  recommendationText: {
    fontSize: 14,
    color: '#333',
    marginLeft: 10,
    flex: 1,
  },
  specialistsContainer: {
    gap: 10,
  },
  specialistButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E3F2FD',
    padding: 15,
    borderRadius: 12,
  },
  specialistButtonText: {
    fontSize: 16,
    color: '#2196F3',
    fontWeight: '500',
    marginLeft: 10,
  },
  disclaimerContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFF3E0',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
  },
  disclaimerText: {
    fontSize: 12,
    color: '#E65100',
    marginLeft: 10,
    flex: 1,
    lineHeight: 16,
  },
  newAnalysisButton: {
    backgroundColor: '#2196F3',
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  newAnalysisButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default AISymptomCheckerScreen;


