/**
 * AI Symptom Checker — server-side Gemini integration.
 *
 * Why this exists: the previous client-side "AI Symptom Checker" screen
 * contained a `setTimeout` returning a hardcoded mock analysis (see git
 * history / code review Critical Issue #5) regardless of user input, while
 * the README advertised "AI-powered symptom analysis using Gemini API."
 * This file is the real implementation of that claim.
 *
 * Design decisions:
 * - The Gemini call happens in a Cloud Function (`onCallGenkit`), never in
 *   the client app, so the `GOOGLE_GENAI_API_KEY` secret is never bundled
 *   into the mobile app or exposed to a reverse-engineered APK/IPA.
 * - `authPolicy` requires the caller to be signed in — an unauthenticated
 *   client cannot invoke (and consume the cost of) this endpoint. This
 *   closes the gap called out in the original code review, where
 *   `authPolicy`/`enforceAppCheck` shipped commented out on the sample
 *   Genkit function this replaces.
 * - Output is constrained to a structured Zod schema so the client can
 *   render it without `any`-typed parsing, and so a malformed/partial model
 *   response fails validation loudly instead of silently rendering
 *   garbage.
 * - A permanent, non-dismissible disclaimer is embedded in the response
 *   itself (not just left to client-side UI) so that even if a future
 *   caller consumes this API directly, the non-diagnostic nature of the
 *   output travels with the data.
 *
 * Known limitation (documented, not hidden): this is a general-purpose
 * LLM prompted for triage-style suggestions, not a validated clinical
 * decision-support tool. It is explicitly out of scope for this project to
 * claim regulatory-grade medical accuracy — see project.md's "Known
 * Limitations" section.
 *
 * Rate limiting: this is the one function in the codebase that both audits
 * specifically called out as needing per-user throttling, since it's a
 * billable third-party API call gated only by authentication (any signed-in
 * account could otherwise drive unbounded Gemini cost). `authPolicy` now
 * consumes a token from a per-uid Firestore-backed token bucket (see
 * rateLimiter.ts) before allowing the call through; a caller who exceeds 5
 * requests (refilling at 5/hour) receives a `resource-exhausted` error.
 *
 * App Check: intentionally not enforced yet — see the note in
 * adminApproval.ts and project.md's "App Check" section for why (no
 * verified native attestation provider wired up for this Expo/React
 * Native client).
 */

import {genkit, z} from "genkit";
import {googleAI, gemini15Flash} from "@genkit-ai/googleai";
import {onCallGenkit} from "firebase-functions/https";
import {defineSecret} from "firebase-functions/params";
import * as logger from "firebase-functions/logger";
import {consumeRateLimitToken} from "./rateLimiter";

const apiKey = defineSecret("GOOGLE_GENAI_API_KEY");

const ai = genkit({
  plugins: [googleAI()],
});

// Exported (rather than kept module-private) specifically so unit tests
// can assert on Zod's rejection behavior directly, without needing to
// invoke the full Genkit flow / Gemini call.
export const SymptomAnalysisInputSchema = z.object({
  symptoms: z.string().min(3).max(2000),
  durationDescription: z.string().max(100).optional(),
  severity: z.enum(["mild", "moderate", "severe"]).optional(),
  additionalInfo: z.string().max(2000).optional(),
});

const PossibleConditionSchema = z.object({
  name: z.string(),
  likelihood: z.enum(["low", "moderate", "high"]),
  description: z.string(),
});

const SymptomAnalysisOutputSchema = z.object({
  possibleConditions: z.array(PossibleConditionSchema).max(5),
  recommendations: z.array(z.string()).max(6),
  suggestedSpecialists: z.array(z.string()).max(4),
  urgency: z.enum(["low", "medium", "high"]),
  disclaimer: z.string(),
});

export type SymptomAnalysisOutput = z.infer<typeof SymptomAnalysisOutputSchema>;

const NON_DIAGNOSTIC_DISCLAIMER =
  "This analysis is generated by an AI model for general informational purposes only. " +
  "It is not a medical diagnosis and must not replace professional medical advice. " +
  "If symptoms are severe or worsening, seek in-person medical care immediately.";

const symptomAnalysisFlow = ai.defineFlow(
  {
    name: "symptomAnalysisFlow",
    inputSchema: SymptomAnalysisInputSchema,
    outputSchema: SymptomAnalysisOutputSchema,
  },
  async (input) => {
    const prompt = `You are a cautious, non-diagnostic health information assistant embedded in a
patient-facing app. A patient describes the following:

Symptoms: ${input.symptoms}
Duration: ${input.durationDescription ?? "not specified"}
Self-reported severity: ${input.severity ?? "not specified"}
Additional info: ${input.additionalInfo ?? "none"}

Respond with a JSON object matching this shape exactly:
{
  "possibleConditions": [{ "name": string, "likelihood": "low"|"moderate"|"high", "description": string }],
  "recommendations": string[],
  "suggestedSpecialists": string[],
  "urgency": "low"|"medium"|"high"
}

Rules:
- List at most 3 possible conditions, ordered most to least likely, and never present them as a confirmed diagnosis.
- Recommendations must be general self-care/next-step guidance, never a specific prescription or dosage.
- Set "urgency" to "high" if symptoms described could indicate a medical emergency (e.g. chest pain,
  difficulty breathing, stroke signs), and say so plainly in the first recommendation.
- Do not repeat the disclaimer in your output; it will be appended separately.`;

    const {output} = await ai.generate({
      model: gemini15Flash,
      prompt,
      output: {
        schema: SymptomAnalysisOutputSchema.omit({disclaimer: true}),
      },
      config: {temperature: 0.2},
    });

    if (!output) {
      throw new Error("The AI model did not return a usable response.");
    }

    return {
      ...output,
      disclaimer: NON_DIAGNOSTIC_DISCLAIMER,
    };
  }
);

/**
 * The `authPolicy` gate for `analyzeSymptoms`, extracted as a standalone
 * exported function so it can be unit-tested directly (rejecting
 * unauthenticated callers, enforcing the rate limit) without needing to
 * invoke the full `onCallGenkit`/Gemini machinery. Rejects unauthenticated
 * callers outright — this is the fix for the commented-out
 * `authPolicy`/`enforceAppCheck` on the sample function this file
 * replaces — and consumes one rate-limit token per call.
 * @param {{uid: string} | null | undefined} auth - The Cloud Functions
 * auth context for the caller, or null/undefined if unauthenticated.
 * @return {Promise<boolean>} Whether the call may proceed.
 */
export async function symptomCheckerAuthPolicy(auth: { uid: string } | null | undefined): Promise<boolean> {
  if (!auth) {
    logger.warn("Rejected unauthenticated symptom analysis request.");
    return false;
  }
  // Throws HttpsError("resource-exhausted", ...) if the caller has no
  // tokens left, which onCallGenkit surfaces directly to the client —
  // this is a deliberately small, billable-API-appropriate budget: 5
  // requests, refilling at a rate of 5 per hour.
  await consumeRateLimitToken(auth.uid, {
    capacity: 5,
    refillRatePerSecond: 5 / 3600,
    action: "analyzeSymptoms",
  });
  return true;
}

/** Callable Cloud Function wrapping `symptomAnalysisFlow`. See `symptomCheckerAuthPolicy` above. */
export const analyzeSymptoms = onCallGenkit(
  {
    secrets: [apiKey],
    enforceAppCheck: false, // see project.md "App Check" — no verified native attestation provider wired up yet
    authPolicy: symptomCheckerAuthPolicy,
  },
  symptomAnalysisFlow
);
